### ISSUE TITLE
Remove indirect notation

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/reimagined-guacamole#10]
Seems like we're able to parse indirect notation using `ArrowIndirectCall`. I suggest we remove it.

**Comment by gonzus** [comment]
Keep in mind that it takes work to make a grammar parse your language, and it takes **a lot more work** to make a grammar parse **only** your language.

**Comment by vickenty** [comment]
Closures and callbacks are pretty common, how else you would invoke them?

**Comment by xsawyerx** [comment]
I'm not sure I follow all the comments.

@vickenty, can you give ma an example of using `ArrowIndirectCall` that is not an indirect object notation?

**Comment by vickenty** [comment]
Sorry, I got confused. So `ArrowIndirectCall` covers code like `$foo->$bar(...)`. I think indirect object notation is different (`new Pkg(...)`).

**Comment by xsawyerx** [comment]
In the case of `$foo->$bar`, `ArrowIndirectCall` makes sense.

Indirect object (or method) notation shouldn't be supported.

Closing the ticket as it was my misunderstanding.
