### ISSUE TITLE
All blocks must end with semicolon, unless last statement

### ISSUE THREAD

**Issue by xsawyerx** [xsawyerx/reimagined-guacamole#44]
[Edit: added all blocks.]

Because subroutines are considered Statements and Statements use Semicolon between them, the following fails:

```perl
sub foo () {...}
sub bar () {...}
```

Instead, it has to be written this way:

```perl
sub foo () {...};
sub bar () {...};
```

This also affects `if()` conditions:

```perl
if ($foo) {1}                          # ok
if ($foo) {1} foo()                    # not ok
if ($foo) {1}; foo()                   # ok
if ($foo) {1} elsif ($bar) {2} foo();  # not ok
if ($foo) {1} elsif ($bar) {2}; foo(); # ok
```

**Comment by gonzus** [comment]
Hum... I think this will cause riots, asking for your head on a pike.

**Comment by xsawyerx** [comment]
Yeah, I agree. :)

**Comment by xsawyerx** [comment]
And @vickenty works his magic yet again! :)
