### ISSUE TITLE
Ambiguity with sort

### ISSUE THREAD

**Issue by vickenty** [xsawyerx/reimagined-guacamole#57]
```
sort $a + $b
```
parses as both:
```
# via OpKeywordSort VarScalar OpListKeywordArg
(sort (varscalar $a) (oplistkeywordarg (exprunary + $b)))

 # via OpKeywordSort OpListKeywordArgNonBrace
(sort (oplistkeywordargnonbrace (expradd '+' (varscalar $a) (varscalar $b)))
```
perl disambiguates to the latter.

This can be fixed with a new expression variant that does not start with an unary operator, similar to `NonBraceExpr` variants, but I'm don't like the idea of duplicating the whole table again.

**Comment by xsawyerx** [comment]
Resolved by #81.
